### PR TITLE
#1

### PR DESCRIPTION
**Pull request by KizeKaze**
Alright teacher, before you dig into this.. in jesus name. My code is a mess but it's functioning as expected. be brutel and let me know what you liked and disliked please.

### CODE REVIEW

**Comment by KizeKaze** [comment]
All form inputs are bootstrap styled.

Todo.js has been adjusted to better fit it's task at hand.

Task table header has been adjusted to remain even if nothing is in the table.

Removed comment on projfile.js line 2. ;o

Removed //commented line 4-8

Adjusted TodosCotnroller->canAccess function, please check if it's what you were looking for.

TodoCollector/Controller should have an empty space at the end since it only contains php code
I don't understand.

Reviewed task.php and corrected line pacing/tabbing to make it easier to look at.

**Comment by KizeKaze** [comment]
updated

**Comment by tony1542** [comment]
Closing for now

**Comment by KizeKaze** [comment]
Moved <form> outside of model body to make it less fucky.

**Comment by KizeKaze** [comment]
Changed description in Add Task to text area instead of input.
Changed title field to not be a text area ;o
Corrected labels on title, description and complete, making them all unique as well.

Updated, everything should now comply with what you asked for.

**Pull request merged**
